define([], function() { return {
  "lui-icon--sheet": "Sheet",
  "lui-icon--object": "Object",
  "lui-icon--image": "Image",
  "lui-icon--clear-selections": "Clear Selections",
  "lui-icon--selections-tool": "Selections Tool",
  "lui-icon--bookmark": "Bookmark",
  "lui-icon--back": "Back",
  "lui-icon--forward": "Forward",
  "lui-icon--history": "History",
  "lui-icon--help": "Help",
  "lui-icon--info": "Info",
  "lui-icon--toggle-left": "Toggle Left",
  "lui-icon--toggle-right": "Toggle Right",
  "lui-icon--selections-reload": "Selections Reload",
  "lui-icon--text": "Text",
  "lui-icon--group": "Group",
  "lui-icon--search": "Search",
  "lui-icon--zoom-in": "Zoom In",
  "lui-icon--zoom-out": "Zoom Out",
  "lui-icon--selections-back": "Selections Back",
  "lui-icon--selections-forward": "Selections Forward",
  "lui-icon--export": "Export",
  "lui-icon--lock": "Lock",
  "lui-icon--unlock": "Unlock",
  "lui-icon--database": "Database",
  "lui-icon--calendar": "Calendar",
  "lui-icon--field": "Field",
  "lui-icon--expression": "Expression",
  "lui-icon--library": "Library",
  "lui-icon--debug": "Debug",
  "lui-icon--script-ok": "Script Ok",
  "lui-icon--grid-large": "Grid Large",
  "lui-icon--star": "Star",
  "lui-icon--print": "Print",
  "lui-icon--remove": "Remove",
  "lui-icon--handle": "Handle",
  "lui-icon--handle-horizontal": "Handle Horizontal",
  "lui-icon--menu": "Menu",
  "lui-icon--list": "List",
  "lui-icon--unordered-list": "Unordered List",
  "lui-icon--bar-chart": "Bar Chart",
  "lui-icon--bar-chart-horizontal": "Bar Chart Horizontal",
  "lui-icon--clock": "Clock",
  "lui-icon--line-chart": "Line Chart",
  "lui-icon--pie-chart": "Pie Chart",
  "lui-icon--gauge-chart": "Gauge Chart",
  "lui-icon--kpi": "Kpi",
  "lui-icon--scatter-chart": "Scatter Chart",
  "lui-icon--map": "Map",
  "lui-icon--puzzle": "Puzzle",
  "lui-icon--table": "Table",
  "lui-icon--pivot-table": "Pivot Table",
  "lui-icon--filterpane": "Filterpane",
  "lui-icon--treemap": "Treemap",
  "lui-icon--combo-chart": "Combo Chart",
  "lui-icon--plus": "Plus",
  "lui-icon--minus": "Minus",
  "lui-icon--triangle-top": "Triangle Top",
  "lui-icon--triangle-bottom": "Triangle Bottom",
  "lui-icon--triangle-left": "Triangle Left",
  "lui-icon--triangle-right": "Triangle Right",
  "lui-icon--run-script": "Run Script",
  "lui-icon--tick": "Tick",
  "lui-icon--cogwheel": "Cogwheel",
  "lui-icon--settings": "Settings",
  "lui-icon--data-model": "Data Model",
  "lui-icon--script": "Script",
  "lui-icon--cut": "Cut",
  "lui-icon--copy": "Copy",
  "lui-icon--paste": "Paste",
  "lui-icon--align-left": "Align Left",
  "lui-icon--align-center": "Align Center",
  "lui-icon--align-right": "Align Right",
  "lui-icon--bold": "Bold",
  "lui-icon--italic": "Italic",
  "lui-icon--underline": "Underline",
  "lui-icon--select-alternative": "Select Alternative",
  "lui-icon--select-possible": "Select Possible",
  "lui-icon--select-excluded": "Select Excluded",
  "lui-icon--select-all": "Select All",
  "lui-icon--camera": "Camera",
  "lui-icon--slide-show": "Slide Show",
  "lui-icon--palette": "Palette",
  "lui-icon--shapes": "Shapes",
  "lui-icon--effects": "Effects",
  "lui-icon--file": "File",
  "lui-icon--expand": "Expand",
  "lui-icon--collapse": "Collapse",
  "lui-icon--bin": "Bin",
  "lui-icon--link": "Link",
  "lui-icon--pivot": "Pivot",
  "lui-icon--reload": "Reload",
  "lui-icon--add": "Add",
  "lui-icon--edit": "Edit",
  "lui-icon--lasso": "Lasso",
  "lui-icon--key": "Key",
  "lui-icon--box": "Box",
  "lui-icon--home": "Home",
  "lui-icon--person": "Person",
  "lui-icon--stream": "Stream",
  "lui-icon--next": "Next",
  "lui-icon--grid": "Grid",
  "lui-icon--cloud": "Cloud",
  "lui-icon--more": "More",
  "lui-icon--import": "Import",
  "lui-icon--folder": "Folder",
  "lui-icon--auto-layout": "Auto Layout",
  "lui-icon--toggle-bottom": "Toggle Bottom",
  "lui-icon--drop": "Drop",
  "lui-icon--play": "Play",
  "lui-icon--tag": "Tag",
  "lui-icon--close": "Close",
  "lui-icon--direct-discovery": "Direct Discovery",
  "lui-icon--warning": "Warning",
  "lui-icon--warning-triangle": "Warning Triangle",
  "lui-icon--share": "Share",
  "lui-icon--top": "Top",
  "lui-icon--low-resolution": "Low Resolution",
  "lui-icon--high-resolution": "High Resolution",
  "lui-icon--view": "View",
  "lui-icon--control": "Control",
  "lui-icon--code": "Code",
  "lui-icon--upload": "Upload",
  "lui-icon--repair": "Repair",
  "lui-icon--split": "Split",
  "lui-icon--up-down": "Up Down",
  "lui-icon--disconnect": "Disconnect",
  "lui-icon--photo-library": "Photo Library",
  "lui-icon--application": "Application",
  "lui-icon--new-tab": "New Tab",
  "lui-icon--ascending": "Ascending",
  "lui-icon--descending": "Descending",
  "lui-icon--arrow-up": "Arrow Up",
  "lui-icon--arrow-down": "Arrow Down",
  "lui-icon--arrow-right": "Arrow Right",
  "lui-icon--arrow-left": "Arrow Left",
  "lui-icon--sync": "Sync",
  "lui-icon--draggable": "Draggable",
  "lui-icon--book": "Book",
  "lui-icon--measure": "Measure",
  "lui-icon--download": "Download",
  "lui-icon--more-rounded": "More Rounded",
  "lui-icon--align-object-left": "Align Object Left",
  "lui-icon--align-object-center": "Align Object Center",
  "lui-icon--align-object-right": "Align Object Right",
  "lui-icon--submit": "Submit",
  "lui-icon--operators": "Operators",
  "lui-icon--general-data-class": "General Data Class",
  "lui-icon--building": "Building",
  "lui-icon--bell": "Bell",
  "lui-icon--unlink": "Unlink",
  "lui-icon--lightbulb": "Lightbulb",
  "lui-icon--associate": "Associate",
  "lui-icon--break-association": "Break Association",
  "lui-icon--log-out": "Log Out",
  "lui-icon--log-in": "Log In",
  "lui-icon--previous": "Previous",
  "lui-icon--mashup": "Mashup",
  "lui-icon--widget": "Widget",
  "lui-icon--goto": "Goto",
  "lui-icon--paperclip": "Paperclip",
  "lui-icon--save": "Save",
  "lui-icon--compass": "Compass"
}; });